### ISSUE TITLE
sudo permissions on Linux

### ISSUE THREAD

**Issue by debegr92** [saeidjoker/libc.hwid#6]
On Linux, the Generate() function needs sudo permissions to run.
There is no async function to wait until the user entered the password for console applications.

**Comment by sfmohassel** [comment]
True, on Linux user needs sudo permissions.
If you [look here](https://github.com/saeidjoker/libc.hwid/blob/8344180be085c2d8207cde365edbaf00acd0df70/libc.hwid/HwId.cs#L81) we pass `true` as the last parameter (waitForExit). It means that the [the code here in Cmd.cs](https://github.com/saeidjoker/libc.hwid/blob/8344180be085c2d8207cde365edbaf00acd0df70/libc.hwid/Cmd.cs#L44) will:
- create a process to run the dmidecode command
- waits for the process to finish and also asks for sudo password at this step (this is triggered by bash automatically in Ubuntu for example)
- returns the result

I'm not sure how an async function is going to help us in these steps.

To better see this in action run these commands:
- `dotnet test (in repository root directory)`
- `cd libc.hwid.runner; dotnet run --framework net6.0`

**Comment by replaysMike** [comment]
I just ran into this as well. The library bails when run within a service on Ubuntu. It would be nice to have a little more control or a fallback if sudo is not available.

**Comment by sfmohassel** [comment]
@replaysMike I don't have any clue on how to do that for now :-( Any contributions are welcome

**Comment by replaysMike** [comment]
I'll look into it, if I can find a solution I'll submit a PR
