### ISSUE TITLE
Do cloned PCs have the same ID ?

### ISSUE THREAD

**Issue by mightypanda** [saeidjoker/libc.hwid#7]
Hello,
In the case of identical PCs with same MotherBoard and CPU, and a clone of the system image, will the generated ID be the same?

**Comment by sfmohassel** [comment]
I assume it would, because windows API are ought to be "reliable"
Unfortunately I do not have the resources to test this exact case

**Comment by arcykojot** [comment]
I have deployed app to client which bought PCs in bulk so they have same configuration over number of PCs. All have same ID.

**Comment by mightypanda** [comment]
This is scary, as I think the same motherboard + cpu combination could be very frequent also for different customers.
So is this not enough of a combination?

**Comment by arcykojot** [comment]
It is not perfect, but it is free. I imagine it is not easy to get serial numbers of hardware for different platforms.

In my app I have implemented also time subscription and versions limits using other libraries. For small things it is enough.

**Comment by mightypanda** [comment]
Absolutely, love this lib!
Can you share which other libraries you used for the licensing itself? Thank you!

**Comment by arcykojot** [comment]
I use this:
https://github.com/CoreCompat/Portable.Licensing
libc generates for me content for AdditionalAtribute in license.

**Comment by sfmohassel** [comment]
@arcykojot Thank you for contributing to this conversation
@mightypanda I'll try to add other features as well, but keep in mind that it would be a lengthy process unfortunately
