### ISSUE TITLE
Question about motherboard and CPU

### ISSUE THREAD

**Issue by jaydubal** [saeidjoker/libc.hwid#8]
Hi, does the same brand/model Motherboard and exact same CPU model, generate the
same hardware id? Thanks.

**Comment by arcykojot** [comment]
Yes.

**Comment by jaydubal** [comment]
Thanks, any reason for not including the "disk/storage media" information for unique ID generation?

**Comment by arcykojot** [comment]
I guess author assumed that storages could be swapped often which would made id invalid.

**Comment by jaydubal** [comment]
Right. Thanks.

**Comment by sfmohassel** [comment]
Thanks @arcykojot for participation. Closing as there's no plan to add this in the foreseeable future
